version: "3.9"

services:
  backend: 
    build: "./"
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=root123
      - USER_DB=workdb
    networks:
      - mynet
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
      - POSTGRES_DB=workdb
    container_name: postgres
    networks:
      - mynet
networks:
  mynet: 

      
